ALTER TABLE `media`
    MODIFY COLUMN `status` ENUM ('MANUAL', 'WAITING', 'DOWNLOADED', 'DOWNLOADING', 'DOWNLOADED_NEED_METADATA', 'PENDING_DELETION', 'DELETED', 'KEEP', 'MANUALLY_DELETED') NOT NULL;
